openapi: 3.0.3
info:
  title: Salesforce Orders API
  description: API for managing Salesforce Orders.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
servers:
  - url: https://your-salesforce-instance.my.salesforce.com
    description: Salesforce Production Server
security:
  - oauth2: []

paths:
  /services/data/vXX.X/sobjects/Order:
    get:
      summary: Get all orders
      description: Retrieves a list of orders from Salesforce.
      responses:
        '200':
          description: A list of orders.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized access.
        '500':
          description: Server error.
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: Number of orders to retrieve.
        - in: query
          name: offset
          schema:
            type: integer
          description: Starting point of the results.

    post:
      summary: Create a new order
      description: Creates a new order in Salesforce.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Order created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad request.
        '401':
          description: Unauthorized access.
        '500':
          description: Server error.

  /services/data/vXX.X/sobjects/Order/{orderId}:
    get:
      summary: Get order by ID
      description: Retrieves details of a specific order by its ID.
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
          description: The ID of the order.
      responses:
        '200':
          description: Order details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found.
        '401':
          description: Unauthorized access.

    patch:
      summary: Update an order
      description: Updates an existing order in Salesforce.
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
          description: The ID of the order.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Order updated successfully.
        '400':
          description: Bad request.
        '404':
          description: Order not found.
        '401':
          description: Unauthorized access.

    delete:
      summary: Delete an order
      description: Deletes an order by its ID.
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
          description: The ID of the order.
      responses:
        '204':
          description: Order deleted successfully.
        '404':
          description: Order not found.
        '401':
          description: Unauthorized access.

components:
  schemas:
    Order:
      type: object
      properties:
        Id:
          type: string
          description: Unique identifier for the order.
        Status:
          type: string
          description: Status of the order.
        AccountId:
          type: string
          description: ID of the account associated with the order.
        TotalAmount:
          type: number
          format: float
          description: Total amount of the order.
        EffectiveDate:
          type: string
          format: date
          description: Effective date of the order.

securitySchemes:
  oauth2:
    type: oauth2
    flows:
      clientCredentials:
        tokenUrl: https://your-salesforce-instance.my.salesforce.com/services/oauth2/token
        scopes:
          read:orders: Read access to orders
          write:orders: Write access to orders
