name: Publish API to Anypoint Exchange

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  publish-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Anypoint CLI
      run: |
        curl -L https://anypoint.mulesoft.com/downloads/cli/anypoint-cli-linux -o anypoint-cli
        chmod +x anypoint-cli
        sudo mv anypoint-cli /usr/local/bin/anypoint-cli

    - name: Login to Anypoint Platform
      env:
        ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
        ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
      run: |
        anypoint-cli --username $ANYPOINT_USERNAME --password $ANYPOINT_PASSWORD login

    - name: Publish API Specification to Exchange
      env:
        ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORG }}
        ANYPOINT_ENVIRONMENT: ${{ secrets.ANYPOINT_ENV }}
      run: |
        anypoint-cli --org-id $ANYPOINT_ORG_ID exchange publish \
          --file path/to/your-api-specification.raml \
          --assetId your-asset-id \
          --groupId your-group-id \
          --version 1.0.0
