name: Github Actions Workflow

on:
  push:
    branches: [ main ]

env:
  ANYPOINT_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
  ANYPOINT_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
  ANYPOINT_ORG: be8a3e1e-16ca-4dc1-b571-36813fc3681b
  ANYPOINT_ENV: Sandbox

jobs:
  anypoint-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Set up NodeJS 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Anypoint CLI
        run: |
          npm install -g anypoint-cli-v4
      - name: List Runtime Manager's applications
        run: |
          anypoint-cli-v4 runtime-mgr:application:list --output json
      - name: Install Anypoint Catalog CLI
        run: |
          npm install -g api-catalog-cli@latest
      - name: "Find and Run Descriptor Command"
        run: |
          find . -type f -name "*.yaml" | while read spec_file; do
            spec_dir=$(cd "$(dirname "$spec_file")" && pwd) # Resolves to absolute path of the directory
            echo "Found specification in $spec_dir"
            api-catalog create-descriptor -d mydescriptor.yaml
          done          
      - name: Publish to exchange
        run: |
          api-catalog publish-asset -d mydescriptor.yaml --force-publish
