name: Github Actions Workflow

on:
  push:
    branches: [ main ]

env:
  ANYPOINT_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
  ANYPOINT_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
  ANYPOINT_ORG: be8a3e1e-16ca-4dc1-b571-36813fc3681b
  ANYPOINT_ENV: Sandbox

jobs:
  anypoint-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Set up NodeJS 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Anypoint CLI
        run: |
          npm install -g anypoint-cli-v4
      - name: Install Anypoint Catalog CLI
        run: |
          npm install -g api-catalog-cli@latest
      - name: "Install yq (YAML Processor)"
        run: |
          sudo apt-get update
          sudo apt-get install -y jq yq
      - name: "Modify Catalog Descriptor"
        run: |
          yq eval '.projects[] |= (if .main then .tags = ["codat", "gcp"] else . end)' -i mydescriptor.yaml
      - name: "Find and Run Descriptor Command"
        run: |
          # find . -type f -name "*.yaml" | while read spec_file; do
            # spec_dir=$(cd "$(dirname "$spec_file")" && pwd) # Resolves to absolute path of the directory
            # echo "Found specification in $spec_dir"
            # api-catalog create-descriptor -d catalog.yaml
            # Add tags to the file
            # echo -e "\ntags:\n  - sys" >> catalog.yaml
          # done          
      # - name: Publish to exchange
        # run: |
          # api-catalog publish-asset -d mydescriptor.yaml --force-publish
