# This is a basic workflow to help you get started with Actions

name: CICD Example

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ main ]
env:
  ANYPOINT_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
  ANYPOINT_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
  ANYPOINT_ORG: be8a3e1e-16ca-4dc1-b571-36813fc3681b
  ANYPOINT_ENV: Sandbox

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Build Ubuntu
    runs-on: ubuntu-latest
    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
    jobs:
      build:
        # Build Ubuntu
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v2
          - name: Install api-catalog cli
            run: |
              sudo apt-get update
              npm install -g api-catalog-cli@latest
          - name: "Install yq (YAML Processor)"
            run: |
              curl -sLo /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.20.2/yq_linux_amd64
              chmod +x /usr/local/bin/yq
          - name: "Find and Run Descriptor Command"
            run: |
                api-catalog create-descriptor -d catalog.yaml
          - name: "Upadte descriptor file with versions and trigger conditions"
            run: |
                yq eval '{
                  "triggerConditions": {
                    "branches": ["main"]
                  },
                  "contact": {
                    "name": "John Doe",
                    "email": "john.doe@org.com"
                  }
                } * .' -i catalog.yaml
          - name: Publish to exchange
        run: |
          api-catalog publish-asset -d catalog.yaml --force-publish --trigger-criteria=branches:main --organization="$ORG_ID" --client_id="$ANYPOINT_CLIENT_ID" --client_secret="$ANYPOINT_CLIENT_SECRET"



